libnetconf2 BUGFIX netopeer2 build fails when building with musl libc
/home/hthiery/sources/mainline/buildroot/output/host/x86_64-buildroot-linux-musl/sysroot/usr/include/libnetconf2/session_server.h:439:55: error: unknown type name ‘mode_t’
  439 | int nc_server_endpt_set_perms(const char *endpt_name, mode_t mode, uid_t uid, gid_t gid);

For musl libc the include "sys/types.h" is required.

Signed-off-by: Heiko Thiery <heiko.thiery@gmail.com>